In [5]:
import struct
from math import log, exp
from array import array
import numpy as np
import random

def read(fname_img, fname_lbl, n):
    f = open(fname_lbl, 'rb')
    magic_nr, size = struct.unpack(">II", f.read(8))
    lbl = array("b", f.read())
    f.close()

    f = open(fname_img, 'rb')
    magic_nr, size, rows, cols = struct.unpack(">IIII", f.read(16))
    img = array("B", f.read())
    f.close()

    tmp = [1]
    img_matrix = []
    for x in img.tolist():
        tmp.append(x)
        if len(tmp) == 785:
            img_matrix.append(tmp)
            tmp = [1]
            if (len(img_matrix) == n):
                break

    return lbl.tolist()[:n], img_matrix


train_size = 60000

train_lbl, train_img = read("train-images-idx3-ubyte", "train-labels-idx1-ubyte", 60000)
test_lbl, test_img = read("t10k-images-idx3-ubyte", "t10k-labels-idx1-ubyte", 20000)

index_shuf = range(train_size)
random.shuffle(index_shuf)
x = []
y = []
for i in range(train_size):
    x.append(train_img[i])
    y.append(train_lbl[i])
train_lbl, train_img = y, x

In [7]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix

clf = svm.LinearSVC()
tmp = OneVsRestClassifier(clf)
tmp.fit(train_img, train_lbl)
result = tmp.predict(test_img)
print confusion_matrix(result, test_lbl)
print clf

[[ 830    0   18   15    2   68   20    2   33    8]
 [   1 1073  191   33    7   23   23   50   72    9]
 [  23    2  590   58    1   15   14   33   41   17]
 [   7    1    7  780    5  214    0   15   53   57]
 [   7    1   99   14  799  114  122   14   78  313]
 [  58    1    5   13    0  263   26    8   18    7]
 [  25    1   17   11   43   45  716    0   41    4]
 [  27    1   21   13   16   33   16  814   14  173]
 [   1   50   78   30   16   80    5   26  481   19]
 [   1    5    6   43   93   37   16   66  143  402]]
LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)


In [8]:
ite = []
train_loss = []
test_loss = []
for l in open("result.txt"):
    i, train, test = l.split(' ')
    ite.append(int(i))
    train_loss.append(float(train))
    test_loss.append(float(test))

In [12]:
import matplotlib.pyplot as plt
plt.plot(ite[5:], train_loss[5:], 'ro')
plt.show()