In [1]:
import struct
from math import log, exp
from array import array
import numpy as np

def read(fname_img, fname_lbl, n):
    f = open(fname_lbl, 'rb')
    magic_nr, size = struct.unpack(">II", f.read(8))
    lbl = array("b", f.read())
    f.close()

    f = open(fname_img, 'rb')
    magic_nr, size, rows, cols = struct.unpack(">IIII", f.read(16))
    img = array("B", f.read())
    f.close()

    tmp = [1]
    img_matrix = []
    for x in img.tolist():
        tmp.append(x)
        if len(tmp) == 785:
            img_matrix.append(tmp)
            tmp = [1]
            if (len(img_matrix) == n):
                break

    return lbl.tolist()[:n], img_matrix


train_size = 2000
test_size = 100

train_lbl, train_img = read("train-images-idx3-ubyte", "train-labels-idx1-ubyte", train_size)
test_lbl, test_img = read("t10k-images-idx3-ubyte", "t10k-labels-idx1-ubyte", test_size)

In [15]:
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix

clf = svm.SVC()
tmp = OneVsRestClassifier(clf)
tmp.fit(train_img, train_lbl)
result = tmp.predict(test_img)
print confusion_matrix(result, test_lbl)
print clf

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 8 14  8 11 14  7 10 15  2 11]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)


In [ ]:
()